config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'key_locations#index'

  resources :key_locations, only: [:create, :update]
  resources :locations
end

app/models/key.rb
class Key < ActiveRecord::Base
  has_one :key_location

  validates_presence_of :name
end

app/models/key_location.rb
class KeyLocation < ActiveRecord::Base
  belongs_to :key
  belongs_to :location

  validates_presence_of :key_id, :location_id
  validates_uniqueness_of :key_id, scope: [:location_id]
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :key_location

  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/key_locations_controller.rb
class KeyLocationsController < ApplicationController

  before_action :set_key_location

  def index
    @key_location = KeyLocation.find_by(key: Key.first) || KeyLocation.new
  end

  def create
    @key_location = KeyLocation.new(key_locations_params)

    if @key_location.save
      redirect_to root_path
    end
  end

  def update
    @key_location.update(key_locations_params)

    redirect_to root_path
  end

  private

  def key_locations_params
    params.require(:key_location).permit(:id, :key_id, :location_id)
  end

  def set_key_location
    @key_location = KeyLocation.find_by_id(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @location = Location.new
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_path, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to locations_path, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/key_locations_helper.rb
module KeyLocationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/key_locations/index.html.slim
.key_locations
  h1 鍵はどこ？
  - Location.all.each do |location|
    = form_for @key_location do |f|
      - is_active = @key_location && @key_location.location == location ? "btn-success" : "btn-default"
      = f.hidden_field :key_id, value: Key.first.id
      = f.hidden_field :location_id, value: location.id
      = f.submit location.name, class: "btn #{is_active}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenChecker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | OpenChecker
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
  body
    #container
      nav#header
        ul.menu
          li = link_to '場所を追加', locations_path
          li = link_to 'ホームに戻る', root_path

        - if user_signed_in?
          li = link_to 'ログアウト', destroy_user_session_path, method: :delete
        - else
          li
            = link_to 'サインイン', new_user_registration_path
            | |
            = link_to 'ログイン', new_user_session_path
      #content
        .info
          p.notice = notice
          p.alert = alert

        = yield
      #footer

app/views/locations/_form.html.slim
.location-form
  = form_for location do |f|
    - if location.errors.any?
      #error_explanation
        h2 = "#{pluralize(location.errors.count, "error")} prohibited this location from being saved:"
        ul
          - location.errors.full_messages.each do |message|
            li = message
  
    = f.label :name, "名前"
    = f.text_field :name
  
    .actions
      = f.submit

app/views/locations/edit.html.slim
h1 名前を変更する

== render 'form', location: @location

= link_to '戻る', locations_path

app/views/locations/index.html.slim
table
  thead
    tr
      th 名前
      th 
      th

  tbody
    - @locations.each do |location|
      tr
        td = location.name
        td = link_to '名前を変える', edit_location_path(location)
        td = link_to '削除する', location, data: {:confirm => '本当に削除するの？？'}, method: :delete

br

== render 'form', location: @location

app/views/locations/new.html.slim
h1 新しい場所を追加する

== render 'form', @location

= link_to 'Back', locations_path

app/views/locations/show.html.slim
p#notice = notice


= link_to 'Edit', edit_location_path(@location)
'|
= link_to 'Back', locations_path